// THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD.
// Regenerated by `payload generate:importmap`. It maps custom component string
// paths in the config to their actual modules for the admin bundle. Empty until
// custom admin components are registered.
export const importMap = {}
